import { StyleSheet } from "react-native";

const snapSyncCommentStyles = StyleSheet.create({
  viewContainer: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 5,
    alignSelf: "stretch",
    marginHorizontal: 24,
  },
  viewSnapSyncCommentUserInfo: {
    display: "flex",
    flexDirection: "row",
    gap: 6,
    alignSelf: "stretch",
  },
  viewUsernameAndIsVerified: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    alignSelf: "stretch",
    flexDirection: "row",
    flex: 1,
  },
  textUsername: {
    fontFamily: "Inter-Bold",
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: 20,
    flexWrap: "wrap",
    flexShrink: 1,
  },
  textReplyUsername: {
    fontFamily: "Inter-SemiBold",
    fontSize: 10,
    fontStyle: "normal",
    fontWeight: "600",
    lineHeight: 16,
    flexWrap: "wrap",
    flexShrink: 1,
  },
  textComment: {
    fontFamily: "Inter-Regular",
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 20,
    flexWrap: "wrap",
    flexShrink: 1,
  },
  viewActionsAndTime: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
    alignSelf: "stretch",
  },
  textTimeAndReply: {
    fontFamily: "Inter-Regular",
    fontSize: 10,
    fontStyle: "normal",
    fontWeight: "500",
    lineHeight: 16,
  },
  viewOwnersLikes: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    alignSelf: "stretch",
    flex: 1,
  },
  viewOtherReplies: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    alignSelf: "stretch",
  },
  textOtherReplies: {
    fontFamily: "Inter-Regular",
    fontSize: 10,
    fontStyle: "normal",
    fontWeight: "500",
    lineHeight: 16,
  },
});

export default snapSyncCommentStyles;
